language: node_js
node_js:
- '0.10'
before_install:
- export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
- export REPO_URL=https://$GH_TOKEN@github.com/timedev/Maze.git
- echo $TRAVIS_COMMIT_MSG
- chmod +x build/publish-ghpages.sh
install:
- npm install
script:
- npm run make
after_success: build/publish-ghpages.sh
env:
  global:
    secure: FLCqY47hj4aD1hjTCvnNQ9XnNIb8nqMnIygOGMmAN6JVRyuqRzykMY/G6q6SqhbW84dXWwFVO+8Heikxq57ZJgbwtzmtSvL627u9F9czbusKtCM+IpsRNWuD4Bq0n0Kc21WeE2bodHZBB1JmnCPachiX0DZ7Qypf1kQhzaZdNKM=
